
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizalizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 19;
  public static final int DOSPT = 15;
  public static final int CADENA = 25;
  public static final int DECIMAL = 24;
  public static final int DIVIDIDO = 21;
  public static final int RSTRING = 8;
  public static final int PARIZQ = 11;
  public static final int PARDER = 12;
  public static final int AT = 4;
  public static final int RINT = 9;
  public static final int POR = 20;
  public static final int TABLE = 6;
  public static final int LLAVEIZQ = 16;
  public static final int LLAVEDER = 17;
  public static final int EOF = 0;
  public static final int DATABASE = 2;
  public static final int RDOUBLE = 7;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 22;
  public static final int USE = 5;
  public static final int CORIZQ = 13;
  public static final int ENTERO = 23;
  public static final int STORE = 3;
  public static final int CORDER = 14;
  public static final int MAS = 18;
  public static final int PTCOMA = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DATABASE",
  "STORE",
  "AT",
  "USE",
  "TABLE",
  "RDOUBLE",
  "RSTRING",
  "RINT",
  "PTCOMA",
  "PARIZQ",
  "PARDER",
  "CORIZQ",
  "CORDER",
  "DOSPT",
  "LLAVEIZQ",
  "LLAVEDER",
  "MAS",
  "MENOS",
  "POR",
  "DIVIDIDO",
  "IDENTIFICADOR",
  "ENTERO",
  "DECIMAL",
  "CADENA"
  };
}

